### ISSUE TITLE
Github CI tries to commit when there is nothing to commit

### ISSUE THREAD

**Issue by rpsu** [sinedied/devto-cli#23]
The publish.yml workflow tries to make a git commit even when it appears like there is nothing to commit. This appears to happens when I've published the posts from my local and the CI updates posts.

```
Run sinedied/publish-devto@v2
/usr/bin/docker run --name db2d7b541e79b11954185a9e3aef5ffeb8abc_8c4255 --label 7db2d7 --workdir /github/workspace 
......
Found 7 article(s)
- Retrieving articles from dev.to…
......
/usr/bin/git add posts/2015/....
/usr/bin/git -c user.name="dev.to bot" -c user.email="sinedied+devtobot@gmail.com" commit -m chore: update published articles [skip ci]
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Error: Error: Cannot commit changes: The process '/usr/bin/git' failed with exit code 1
```
and the `publish.yml`  file I have:
```yaml
# This workflow will push and update articles on dev.to each time a new
# commit is pushed to the main branch.
#
# To make it work, you need a dev.to API key, see:
# https://docs.dev.to/api/#section/Authentication/api_key
#
# Once you have generated the token, you need to add them as a secret in your
# GitHub repository:
# - DEVTO_TOKEN: your dev.to API key
# See https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets
# for more information about GitHub secrets.

name: publish
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Publish articles on dev.to
      uses: sinedied/publish-devto@v2
      with:
        # Your dev.to personal API key to publish and update articles.
        # See https://docs.dev.to/api/#section/Authentication/api_key
        devto_key: ${{ secrets.DEVTO_TOKEN }}
        # Your GitHub personal access token, used to create commits for updated files.
        # If you have a protected branch, you need to create a commit with the
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # (Optional) The files to publish. Default is "posts/**/*.md"
        files: 'posts/**/*.md'
        # (Optional) The git branch to use. Default is 'main'.
        branch: main
        # (Optional) Use conventional commit messages. Default is false.
        # See https://www.conventionalcommits.org. 
        conventional_commits: true
```
